import { StyleSheet } from 'react-native';

export const createGlobalStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.secondary,
      paddingHorizontal: 16,
      paddingTop: 24,
      paddingBottom: 80,
    },
    card: {
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    cardOverdue: {
      borderColor: colors.error,
    },
    cardCompleted: {
      borderColor: colors.accent,
      opacity: 0.7,
    },
    settingsCard: {
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    addButton: {
      backgroundColor: colors.primary,
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
      marginVertical: 16,
    },
    addButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: '600',
    },
    title: {
      color: colors.text,
      fontSize: 28,
      fontWeight: 'bold',
      marginBottom: 16,
    },
    bodyText: {
      color: colors.text,
      fontSize: 16,
    },
    captionText: {
      color: colors.text,
      fontSize: 14,
      opacity: 0.7,
    },
    overdueText: {
      color: colors.error,
      fontSize: 14,
      fontWeight: 'bold',
    },
    markButton: {
      backgroundColor: colors.primary,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: 'center',
    },
    markButtonCompleted: {
      backgroundColor: colors.accent,
    },
    markButtonText: {
      color: colors.background,
      fontSize: 14,
      fontWeight: '600',
    },
    switch: {
      trackColor: { false: colors.border, true: colors.accent },
      thumbColor: colors.background,
    },
    navBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 8,
      backgroundColor: colors.background,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    navItem: {
      alignItems: 'center',
      flex: 1,
      paddingVertical: 4,
    },
    navItemActive: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      padding: 8,
    },
    navText: {
      color: colors.text,
      fontSize: 11,
      marginTop: 2,
    },
    navTextActive: {
      color: colors.background,
      fontWeight: '600',
    },
  });