import { StyleSheet } from 'react-native';

export const createGlobalStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.secondary,
      paddingHorizontal: 16,
      paddingTop: 24,
      paddingBottom: 80,
    },
    card: {
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      elevation: 3,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    cardOverdue: {
      borderColor: colors.error,
    },
    cardCompleted: {
      borderColor: colors.accent,
      opacity: 0.7,
    },
    settingsCard: {
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      elevation: 3,
    },
    addButton: {
      backgroundColor: colors.primary,
      borderRadius: 50,
      width: 56,
      height: 56,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      bottom: 100,
      right: 16,
      boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
      elevation: 5,
    },
    addButtonText: {
      color: colors.background,
      fontSize: 24,
      fontWeight: 'bold',
    },
    cardActions: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
    },
    title: {
      color: colors.text,
      fontSize: 28,
      fontWeight: 'bold',
      marginBottom: 16,
    },
    bodyText: {
      color: colors.text,
      fontSize: 16,
    },
    captionText: {
      color: colors.text,
      fontSize: 14,
      opacity: 0.7,
    },
    overdueText: {
      color: colors.error,
      fontSize: 14,
      fontWeight: 'bold',
    },
    markButton: {
      backgroundColor: colors.primary,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: 'center',
    },
    markButtonCompleted: {
      backgroundColor: colors.accent,
    },
    markButtonText: {
      color: colors.background,
      fontSize: 14,
      fontWeight: '600',
    },
    actionButton: {
      padding: 8,
      marginLeft: 8,
    },
    calendar: {
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      elevation: 3,
    },
    input: {
      backgroundColor: colors.background,
      borderRadius: 8,
      padding: 12,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.text,
      fontSize: 16,
    },
    picker: {
      backgroundColor: colors.background,
      borderRadius: 8,
      padding: 12,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      height: 46,
      justifyContent: 'center',
    },
    switch: {
      trackColor: { false: colors.border, true: colors.accent },
      thumbColor: colors.background,
    },
    navBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 8,
      backgroundColor: colors.background,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      boxShadow: '0 -2px 4px rgba(0,0,0,0.1)',
      elevation: 5,
    },
    navItem: {
      alignItems: 'center',
      flex: 1,
      paddingVertical: 4,
    },
    navItemActive: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      padding: 8,
    },
    navText: {
      color: colors.text,
      fontSize: 11,
      marginTop: 2,
    },
    navTextActive: {
      color: colors.background,
      fontWeight: '600',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
      maxHeight: '50%',
    },
    modalItem: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
  });